name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GHC with Stack
        uses: haskell/actions/setup@v1
        with:
          stack-version: 'latest'
          ghc-version: '8.10.7'

      - name: Install dependencies
        run: stack setup

      - name: Build the project
        run: stack build

      - name: Run tests
        run: stack test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports/

