name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up GHC and Stack
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.6'  # Match your project's GHC version
        stack-version: 'latest'
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev

    - name: Install dependencies
      run: |
        stack setup
        stack build --only-dependencies

    - name: Build
      run: stack build --test --no-run-tests

    - name: Run tests
      run: stack test

    - name: Check formatting (optional)
      run: |
        if command -v stylish-haskell >/dev/null 2>&1; then
          stylish-haskell -r . -i
        else
          echo "stylish-haskell not installed, skipping format check"
        fi

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          .stack-work/dist/**/build/OptionPricingSim-test/OptionPricingSim-test.log
          test-reports/
        retention-days: 7